src/tv2-common/content/server.ts, src/tv2-common/parts/server.ts
Depends on https://github.com/olzzon/tv-automation-sofie-blueprints-integration/pull/5
=> feat: server timing from media objects

.circleci/config.yml, Dockerfile, docker-entrypoint.sh, package.json, yarn.lock
Applying build to Dockerhub and version control
=> Featdockerhub

rundowns/post-deploy-test.json, src/tv2-common/actions/executeAction.ts, src/tv2-common/blueprintConfig.ts, src/tv2-common/content/dve.ts, src/tv2-common/cues/ekstern.ts, src/tv2-common/helpers/sisyfos.ts, src/tv2-common/migrations/index.ts, src/tv2-common/migrations/sourceManifest.ts, src/tv2-common/sources.ts, src/tv2_afvd_showstyle/__tests__/blueprint.spec.ts, src/tv2_afvd_showstyle/__tests__/configs.ts, src/tv2_afvd_showstyle/getRundown.ts, src/tv2_afvd_studio/__tests__/config-manifest.spec.ts, src/tv2_afvd_studio/__tests__/segmentContext.mock.ts, src/tv2_afvd_studio/config-manifests.ts, src/tv2_afvd_studio/helpers/sources.ts, src/tv2_offtube_showstyle/__tests__/actionExecutionContext.mock.ts, src/tv2_offtube_showstyle/getRundown.ts, src/tv2_offtube_studio/__tests__/config-manifest.spec.ts, src/tv2_offtube_studio/config-manifests.ts, src/tv2_offtube_studio/helpers/sources.ts, src/tv2_offtube_studio/migrations/index.ts
A FEED acts the same way as LIVE in Sofie. It has a separate config table.
Usage: `EKSTERN=FEED X`
=> feat: add FEED iNews cue support

src/tv2-common/inewsConversion/converters/ParseBody.ts, src/tv2-common/inewsConversion/converters/__tests__/body-parser.spec.ts
iNews Graphics Test Cases # 24
=> fix: make a graphic part when engine selection precedes red text

src/tv2-common/updatePolicies/index.ts, src/tv2-common/updatePolicies/partProperties.ts, src/tv2-common/updatePolicies/pieces.ts, src/tv2-common/updatePolicies/syncIngestUpdateToPartInstance.ts, src/tv2_afvd_showstyle/__tests__/syncContext.mock.ts, src/tv2_afvd_showstyle/__tests__/syncIngestChangesToPartInstance.spec.ts, src/tv2_afvd_showstyle/syncIngestUpdateToPartInstance.ts, src/tv2_offtube_showstyle/syncIngestUpdateToPartInstances.ts
Handle multiple pieces on a layer
Update allowed part properties
=> fix: sync updates to part instance

src/tv2-common/actions/executeAction.ts, src/tv2_afvd_showstyle/helpers/pieces/jingle.ts
This got missed at some point, we should be replacing adlibs with actions as much as possible.
=> fix: Change jingle adlib to be an action

src/tv2_afvd_showstyle/getRundown.ts, src/tv2_offtube_showstyle/getRundown.ts
Port of this PR https://github.com/tv2/sofie-blueprints-inews/pull/73 to release 37.0.
=> Feat/sof 539/setting showstyle variant from graphic profile port to 37

src/inews-mixins/__tests__/playlist.spec.ts, src/tv2_afvd_showstyle/getRundown.ts, src/tv2_offtube_showstyle/getRundown.ts
Facilitates this PR https://github.com/tv2/inews-ftp-gateway/pull/33 by using the payload to determine showstyle variant.
=> Feat/sof 539/setting showstyle variant from graphic profile

.gitignore, README.md, rundowns/.gitignore, rundowns/convert.js, rundowns/upload.sh
Simplify commands for convert.js 
Possible to specify another studioId for upload script
=> Simplify ingest Rundown to local Sofie environment

src/tv2_afvd_showstyle/getRundown.ts, src/tv2_offtube_showstyle/getRundown.ts
Implementing the changes from https://github.com/tv2/inews-ftp-gateway/pull/37.
=> fix: Renamed graphicProfile to showstyleVariant for IngestRundown payload.

src/tv2-common/hotkeys/global.ts, src/tv2-common/hotkeys/hotkey-defaults.ts, src/tv2-common/hotkeys/rundownView.ts
Last DVE: wrong source layer
Last Live: wrong key
Deactivate and "cut to box": key typos
Should this go to staging or develop?
=> fix: some broken actions triggers

src/tv2-common/updatePolicies/pieces.ts, src/tv2_afvd_showstyle/__tests__/syncIngestChangesToPartInstance.spec.ts
The issue fixed here turned out not to be a direct cause of SOF-849, but it still lead to failing to commit ingest changes made to the partInstances in some cases. 
Removing pieces created by AdLibs caused an error to be thrown by core when we tried to update them later.
=> fix: SOF-849 removing too many pieces

package.json, shelf-layouts/AFVD_Default_showstyle_hotkeys.json, src/tv2-common/hotkeys/helpers/cutToBox.ts, src/tv2-common/hotkeys/helpers/queue.ts, src/tv2-common/hotkeys/helpers/studioSource.ts, src/tv2-common/hotkeys/hotkey-defaults.ts, src/tv2-common/hotkeys/local.ts, src/tv2-common/hotkeys/server.ts, src/tv2_afvd_showstyle/getRundown.ts, yarn.lock
Default shortcuts for EVS (queue and cut_to_box) have been updated.
It is dependent on https://github.com/nrkno/sorensen/pull/2.
=> Sof 823/evs shortcuts incorrectly configured

src/tv2-common/blueprintConfig.ts, src/tv2-common/getSegment.ts, src/tv2-common/inewsConversion/converters/ParseCue.ts, src/tv2-common/types/inews.ts, src/tv2_afvd_showstyle/__tests__/config-manifest.spec.ts, src/tv2_afvd_showstyle/__tests__/configs.ts, src/tv2_afvd_showstyle/config-manifests.ts, src/tv2_offtube_showstyle/__tests__/config-manifest.spec.ts, src/tv2_offtube_showstyle/config-manifests.ts
Able to parse DESIGN_LAYOUT and DESIGN_BG cues from iNews. Implemented inital draft of Schema/Design config
=> SOF-693 Change Design from iNews

package.json, src/tv2-common/helpers/dsk.ts, src/tv2-common/migrations/graphic-defaults.ts, src/tv2-common/migrations/index.ts, src/tv2-common/migrations/sourceManifest.ts, src/tv2_afvd_showstyle/config-manifests.ts, src/tv2_afvd_showstyle/migrations/index.ts, src/tv2_afvd_studio/config-manifests.ts, src/tv2_offtube_showstyle/config-manifests.ts, src/tv2_offtube_showstyle/migrations/index.ts, src/tv2_offtube_studio/config-manifests.ts
**Fixes**
- Default value and migration for ensuring correct bundright configuration.
-  Changed deprecated `ConfigManifestEntryType.NUMBER` to `ConfigManifestEntryType.INT`.
=> Sof 922/migrate bundright

src/tv2-common/actions/executeAction.ts
Dont cut to boxes on current DVE if the current DVE has stopped playback
=> SOF-903 adLib camera locks DVE

src/tv2-common/actions/executeAction.ts, src/tv2-common/content/server.ts, src/tv2-common/parts/server.ts, src/tv2_afvd_showstyle/helpers/pieces/adlib.ts, src/tv2_afvd_showstyle/parts/server.ts, src/tv2_offtube_showstyle/cues/OfftubeAdlib.ts, src/tv2_offtube_showstyle/parts/OfftubeServer.ts
also server adlibs (ADLIBPIX=SERVER) should accept persistence
=> SOF-932: Server adlibs and VO parts should have VO-level audio

package.json, src/tv2-common/actions/executeAction.ts, src/tv2-common/content/jingle.ts, src/tv2-common/helpers/graphics/InternalGraphic.ts, src/tv2-common/hotkeys/hotkey-defaults.ts, src/tv2-common/inewsConversion/converters/ParseBody.ts, src/tv2-common/inewsConversion/converters/__tests__/body-parser.spec.ts, src/tv2_afvd_showstyle/helpers/pieces/__tests__/telefon.spec.ts, src/tv2_afvd_showstyle/helpers/pieces/clearGrafiks.ts, src/tv2_offtube_showstyle/cues/OfftubeJingle.ts, src/tv2_offtube_studio/layers.ts, src/tv2_offtube_studio/migrations/index.ts, src/tv2_offtube_studio/migrations/mappings-defaults.ts
Brings all the fixes that were done on staging
=> Staging -> Develop

src/tv2-common/blueprintConfig.ts, src/tv2_afvd_showstyle/__tests__/config-manifest.spec.ts, src/tv2_afvd_showstyle/__tests__/configs.ts, src/tv2_afvd_showstyle/config-manifests.ts, src/tv2_afvd_showstyle/getRundown.ts, src/tv2_afvd_showstyle/getSegment.ts, src/tv2_afvd_showstyle/helpers/config.ts, src/tv2_offtube_showstyle/helpers/config.ts
Rename attributes of GraphicsSetups configuration table + add new column. 
Rename GrpahicsINewsCode configuration to SelectedGraphicsSetupName as of the current implementation it has no relation to iNews
=> fix: SOF-959 Updating GraphicsSetups configuration table

src/tv2-common/actions/executeAction.ts, src/tv2-common/evaluateCues.ts, src/tv2-common/helpers/graphics/InternalGraphic.ts, src/tv2-common/helpers/graphics/internal/index.ts, src/tv2-common/helpers/graphics/pilot/index.ts, src/tv2-common/helpers/graphics/viz/index.ts, src/tv2_afvd_showstyle/helpers/pieces/__tests__/grafikViz.spec.ts, src/tv2_afvd_showstyle/helpers/pieces/graphic.ts, src/tv2_afvd_showstyle/helpers/pieces/graphicPilot.ts, src/tv2_afvd_showstyle/helpers/pieces/telefon.ts, src/tv2_offtube_showstyle/cues/OfftubeGraphics.ts, yarn.lock
Adds adlib generation for manual Pilot graphics (M timing), example: MOSART=L|**M**|00:10
=> fix: SOF-854 generate adlib for manual pilots

shelf-layouts/Kommentator.json, shelf-layouts/Mini_Shelf_Layout.json, shelf-layouts/Q flow.json, shelf-layouts/Shortcuts and adlib scroll.json
Sets `"toggleOnSingleClick": true` on all dashboard panels (filters)
=> chore: SOF-769 enable single click to toggle adlibs

src/tv2-common/actions/executeAction.ts, src/tv2-common/pieces/adlibServer.ts
Disable Server Resume until fixed
=> fix: SOF-767 temporarily disable Server Resume

shelf-layouts/List.json, shelf-layouts/Streamdeck.json, shelf-layouts/dve controls.json, shelf-layouts/inspect all adlibs.json, src/tv2_afvd_studio/config-manifests.ts, src/tv2_afvd_studio/migrations/index.ts
- `"regionId": "shelf_layouts"` has been added to multiple shelf layouts.
- Changed EPSIO atem channel from 30 to 25 (based on Gallery D setup).
=> Small fixes from v42 test

src/tv2-common/actions/executeAction.ts, src/tv2-common/content/dve.ts
The `videoId` is not required for a valid DVE with `SERVER`. The source assignment is made later.
Note: I'm not refactoring out the `videoId` param because I think it will be needed for SOF-572.
=> fix: SOF-938 server not appearing in DVE

shelf-layouts/Kommentator.json
In the big sync there were changes to how scaling scales and the kommentator view needs to be updated with new values
=> chore:SOF-1043 update scaling. Rename Sisyfos to mic tally

shelf-layouts/Shortcuts and adlib scroll.json
While testing version 42 in gallery with a producer we made slight changes to the shelf layout. Here are those changes
=> chore: SOF-1133 Update shelf layout values

shelf-layouts/Mini_Shelf_Layout.json, shelf-layouts/Rundown_Header_Layout.json, shelf-layouts/Rundown_View_Layout.json
Due to changes in https://github.com/tv2/tv-automation-server-core/pull/176 we need to expose 'isDefaultLayout' on our Layouts
=> SOF-1139 Update layout with 'isDefaultLayout'

package.json, src/tv2-common/__tests__/EvaluateCueTelemetrics.spec.ts, src/tv2-common/cues/EvaluateCueTelemetrics.ts, src/tv2-common/evaluateCues.ts, src/tv2-common/inewsConversion/converters/ParseCue.ts, src/tv2-common/inewsConversion/converters/__tests__/cue-parser.spec.ts, src/tv2-constants/enums.ts, src/tv2_afvd_showstyle/helpers/pieces/evaluateCues.ts, src/tv2_afvd_showstyle/layers.ts, src/tv2_afvd_showstyle/migrations/sourcelayer-defaults.ts, src/tv2_afvd_studio/layers.ts, src/tv2_afvd_studio/migrations/mappings-defaults.ts, src/tv2_offtube_showstyle/migrations/sourcelayer-defaults.ts, yarn.lock
Blueprints is now able to parse 'ROBOT' commands from iNews and convert them to Telemetrics blueprint pieces.
Added layers for Telemetrics
=> Sof 811/Parsing robotic commands from iNews

.github/workflows/automerge.yml
refactor: copied workflow from Core to here.
=> SOF-1151 - Duplicated workflow from Core.

src/tv2-common/helpers/rundownAdLibActions.ts, src/tv2-constants/enums.ts
All transition now also have a NEXT_TAKE_WITH_TRANSITION actionTrigger created.
Refactored RundownAdLibActions to use less duplication
=> SOF-1103 Able to create on next take transition action trigger

src/tv2-common/helpers/rundownAdLibActions.ts
Create expected jingle media for transtions that have a number for a name
=> SOF-1242 Cherry pick to staging

config/webpack.config.js, package.json, src/tv2-common/helpers/__tests__/serverResume.spec.ts, src/tv2_afvd_showstyle/__tests__/syncIngestChangesToPartInstance.spec.ts, yarn.lock
Bump blueprints-integration version to 46.1. Fix compiler issues
=> chore: SOF-1281 Bump version to 46.1

package.json, src/tv2-common/actions/executeAction.ts, src/tv2-common/blueprintConfig.ts, src/tv2-common/helpers/config.ts, src/tv2-common/helpers/graphics/caspar/index.ts, src/tv2-common/helpers/graphics/design/index.ts, src/tv2-common/helpers/graphics/layers.ts, src/tv2-common/helpers/graphics/name.ts, src/tv2-common/helpers/graphics/timing.ts, src/tv2-common/helpers/graphics/viz/index.ts, src/tv2-common/inewsConversion/converters/ParseCue.ts, src/tv2-common/migrations/renameConfigurationHelper.ts, src/tv2-common/showstyle/config-manifests.ts, src/tv2_afvd_showstyle/__tests__/config-manifest.spec.ts, src/tv2_afvd_showstyle/__tests__/configs.ts, src/tv2_afvd_showstyle/__tests__/grafikConfigDefault.ts, src/tv2_afvd_showstyle/config-manifests.ts, src/tv2_afvd_showstyle/getRundown.ts, src/tv2_afvd_showstyle/getSegment.ts, src/tv2_afvd_showstyle/helpers/config.ts, src/tv2_afvd_showstyle/helpers/pieces/__tests__/lyd.spec.ts, src/tv2_afvd_showstyle/helpers/pieces/__tests__/telefon.spec.ts, src/tv2_afvd_showstyle/helpers/pieces/clearGrafiks.ts, src/tv2_afvd_showstyle/helpers/pieces/graphicBackgroundLoop.ts, src/tv2_afvd_showstyle/migrations/index.ts, src/tv2_afvd_showstyle/migrations/util.ts, src/tv2_offtube_showstyle/__tests__/config-manifest.spec.ts, src/tv2_offtube_showstyle/config-manifests.ts, src/tv2_offtube_showstyle/helpers/config.ts, src/tv2_offtube_showstyle/migrations/index.ts
Rename Graphics to GFX for GraphicsSetup and SelectedGraphicsSetup. 
Rename Overlay to GFX for OverlayShowMapping.
Refactored a bunch of variables to reflect the name changes.
=> SOF-1277 Rename config items in blueprints configuration

docs/DVE.md, src/tv2-common/cues/mixMinus.ts, src/tv2-common/helpers/dsk.ts, src/tv2-common/videoSwitchers/TriCaster.ts, src/tv2-common/videoSwitchers/types.ts, src/tv2_afvd_studio/config-manifests.ts, src/tv2_offtube_studio/config-manifests.ts
(requires Bumping blueprints- integration to build properly)
=> SOF-1260 small TriCaster-related fixes

config/webpack.config.js, package.json, src/tv2-common/videoSwitchers/TriCaster.ts, src/tv2-common/videoSwitchers/types.ts, yarn.lock
Bumps blueprints-integration to get the thing building.
Some linting happened too - I think we lost the pre-commit hook at some point - this needs to be looked into.
=> chore: bump blueprints-integration

src/__mocks__/context.ts, src/tv2-common/__tests__/onTimelineGenerate.spec.ts, src/tv2-common/actions/__tests__/executeAction.spec.ts, src/tv2-common/actions/executeAction.ts, src/tv2-common/cues/ekstern.ts, src/tv2-common/evaluateCues.ts, src/tv2-common/helpers/graphics/internal/InternalGraphic.ts, src/tv2-common/helpers/graphics/pilot/PilotGraphicGenerator.ts, src/tv2-common/onTimelineGenerate.ts, src/tv2-common/parts/server.ts, src/tv2-constants/enums.ts, src/tv2_afvd_showstyle/GlobalAdlibActionsGenerator.ts, src/tv2_afvd_showstyle/getRundown.ts, src/tv2_afvd_showstyle/helpers/pieces/__tests__/grafikViz.spec.ts, src/tv2_afvd_showstyle/helpers/pieces/__tests__/telefon.spec.ts, src/tv2_afvd_showstyle/helpers/pieces/dve.ts, src/tv2_afvd_showstyle/parts/kam.ts, src/tv2_afvd_studio/layers.ts, src/tv2_offtube_showstyle/cues/OfftubeDVE.ts, src/tv2_offtube_showstyle/cues/OfftubeJingle.ts, src/tv2_offtube_showstyle/parts/OfftubeKam.ts, yarn.lock
Refactors persisted audio not to collect excessively nested data, which caused mongo errors.
=> fix: SOF-1444 prevent crashing after 180 camera cuts

.husky/pre-commit, package.json, yarn.lock
=> chore: fix lint-staged pre-commit hook

src/tv2-common/actions/actionTypes.ts, src/tv2-common/actions/executeAction.ts, src/tv2-common/cues/lyd.ts, src/tv2-constants/enums.ts, src/tv2_afvd_showstyle/GlobalAdlibActionsGenerator.ts, src/tv2_afvd_showstyle/getRundown.ts
Able to create action triggers to fade the sound bed.
The duration of the fade is dependent on the "trigger mode" value given to the action trigger
=> SOF-1105 Now able to create an action trigger to fade the sound bed

src/__mocks__/context.ts, src/tv2-common/actions/actionTypes.ts, src/tv2-common/actions/executeAction.ts, src/tv2-common/evaluateCues.ts, src/tv2-constants/enums.ts, src/tv2_afvd_showstyle/GlobalAdlibActionsGenerator.ts, src/tv2_afvd_showstyle/getRundown.ts, src/tv2_offtube_showstyle/getRundown.ts
Adds an adlib action that stops Tema graphics and takes the temaud (OUT_TEMA_H) template.
(the tag to look for when defining triggers is `gfx_temaud`)
=> feat: SOF-772 add temaud adlib action

src/tv2-common/content/dve.ts, src/tv2-common/helpers/graphics/caspar/util.ts, src/tv2_afvd_showstyle/config-manifests.ts
Allows for specifying locator type (e.g. `locators` or `locators-afvb`) for HTML graphics.
=> Sof 1502/use animatable dve locators

src/tv2_afvd_showstyle/getRundown.ts, src/tv2_afvd_showstyle/helpers/pieces/clearGrafiks.ts, src/tv2_afvd_showstyle/helpers/pieces/graphicBackgroundLoop.ts, src/tv2_afvd_showstyle/helpers/pieces/routing.ts
Added missing piece metadata.type properties to clear commands, viz routing and background loops.
=> SOF-1623: Added missing piece metadata.type properties to clear commands, viz routing and background loops.

src/tv2-common/getSegment.ts
Segments with MiniShelfs now have the videoClipFileName of the MiniShelf in its metadata
=> SOF-1719 Expose MiniShelf data on Segment

src/tv2-common/cues/gfx-schema-generator.ts
Our CasparCgDesignValues is not allowed to have a whitespace in its name.
This will notify Core with an error when CasparCgDesignValues has a whitespace in the name.
Due to the rigid nature of how Core expose "validation" of JSON configuration, we had to come up with an alternative approach to validate that the values within the JSON object is correct.
This approach checks whether all of CasparCgDesignValues has valid data when the load the CasparCgDesignValue used for the baseline. The baseline is being loaded everytime we ingest from iNews, so this validation will run every time we ingest.
Note: These changes only show the error in old Core.
=> SOF-1789 Notify user about incorrect CasparCgDesignValues

src/tv2-common/inewsConversion/converters/ParseBody.ts
Fixed slutord bug where it once generated a kam part.
=> Fixed end word parsing
