tv2/sofie-blueprints-inews

- src/tv2_afvd_showstyle/helpers/content/dve.ts
- src/tv2_afvd_showstyle/helpers/pieces/ekstern.ts
- src/tv2_afvd_showstyle/helpers/sisyfos/sisyfos.ts
- src/tv2_afvd_showstyle/parts/kam.ts
fix: Stereo sources are handled in Sisyfos, so only one cfader needs to be handled in Blueprint
fix: faderLevel: 0.75 should only be used on Server and Jingles
feat: voiceOverLevel: true/false added in sisyfos.ts
feat: GetSisyfosTimelineObjFadeToBlack() added in sisyfos.ts - to be implemented when resetting manuallly added sources between segments
> feat/sisfos-audio:

- src/tv2_afvd_showstyle/getRundown.ts
This PR adds support for sending custom commands to Viz Engines in order to fully clear them.
Names of channels that need to be cleared are added in `channelsToSendCommands` of `TimelineObjVIZMSEClearAllElements` in the _GFX Clear_ AdLib.
It depends on https://github.com/olzzon/tv-automation-state-timeline-resolver/pull/14
> feat: Clear Viz Engines in GFX Clear

- src/tv2-common/cues/viz.ts
- src/tv2_afvd_showstyle/getRundown.ts
- src/tv2_afvd_showstyle/helpers/pieces/__tests__/grafikViz.spec.ts
- src/tv2_afvd_showstyle/helpers/pieces/__tests__/telefon.spec.ts
- src/tv2_afvd_showstyle/helpers/pieces/design.ts
- src/tv2_afvd_showstyle/helpers/pieces/grafikViz.ts
- src/tv2_afvd_showstyle/helpers/pieces/mos.ts
This PR adds support for statuses of graphics. 
All GraphicsContents except Pilot and Offtube fulls have `ignoreMediaObjectStatus` set to true. Pilot's GraphicsContent have a `fileName` that will match the `mediaId` in MediaObjects.
Depends on https://github.com/olzzon/tv-automation-sofie-blueprints-integration/pull/3
> feat: Add graphics status support

- src/tv2-common/cueTiming.ts
- src/tv2_afvd_showstyle/helpers/pieces/grafikViz.ts
- src/tv2_offtube_showstyle/cues/OfftubeGrafikCaspar.ts
This PR fixes how `lifespan` is set for Ident pieces. It was `OutOnSegmentEnd`, now it is `WithinPart` by default, but it can be overwritten by setting outtime in iNews.
> fix: Ident piece lifespan

- src/tv2_afvd_showstyle/helpers/pieces/__tests__/lyd.spec.ts
- src/tv2_afvd_showstyle/helpers/pieces/lyd.ts
Don't generate a piece, generate a warning only.
> fix: Ignore LYD where soundbed is not found in config table

- docs/cues.md
- rundowns/offtubes-reference.json
- src/tv2-common/evaluateCues.ts
- src/tv2-common/inewsConversion/converters/ParseCue.ts
- src/tv2-common/inewsConversion/converters/__tests__/cue-parser.spec.ts
- src/tv2-constants/enums.ts
- src/tv2_offtube_showstyle/cues/OfftubePgmClean.ts
- src/tv2_offtube_showstyle/helpers/EvaluateCues.ts
- src/tv2_offtube_showstyle/layers.ts
- src/tv2_offtube_showstyle/migrations/sourcelayer-defaults.ts
Selects what to send to the Clean Pgm AUX output on the ATEM. It's meant to be used in Klar on Air.
Currently only `PGM` and `LIVE 1` are supported, but with small changes in the parsing logic, it could support any source.
If this cue is not provided, the outputs default to `PGM` equivalent.
Example: `PGMCLEAN=LIVE 1`
> feat: Add PGMCLEAN iNews cue support (Offtube)

- src/tv2-common/actions/executeAction.ts
If there is a piece on a sourceLayer other than Effect, take it as the primary - only if there isn't, the part is a jingle.
> fix: transition replacement on take with transition

- src/tv2_offtube_showstyle/__tests__/actionExecutionContext.mock.ts
- src/tv2_offtube_studio/__tests__/config-manifest.spec.ts
- src/tv2_offtube_studio/config-manifests.ts
- src/tv2_offtube_studio/getBaseline.ts
- src/tv2_offtube_studio/helpers/config.ts
Allows selecting sisyfos layers for which the channel fader will be up at PGM level in studio baseline. Defaults to LIVE 1 layers to match the `IdleSource` default.
> feat: Add IdleSisyfosLayers config manifest entry (Offtube)

- src/tv2-constants/enums.ts
- src/tv2_afvd_showstyle/getRundown.ts
- src/tv2_afvd_showstyle/helpers/pieces/lyd.ts
- src/tv2_afvd_studio/layers.ts
- src/tv2_afvd_studio/migrations/mappings-defaults.ts
- Adds support for /LYD=Fade (\d+)/ cues
- Adlib cues will stop soundbed pieces and fade out the soundbed
- Pre-programmed fades will fade out the soundbed that is playing at that point in the script
- Changes soundbeds to OnRundownChange infinites, as these are the only ones that can be interrupted by WithinPart pieces in the same part. This also means the soundbed won't play until taken, which has been requested as the behaviour
> feat: Add audio bed fade cues

- src/tv2-common/actions/actionTypes.ts
- src/tv2-common/actions/executeAction.ts
- src/tv2-common/content/server.ts
- src/tv2-common/getSegment.ts
- src/tv2-common/parts/server.ts
- src/tv2-common/pieces/adlibServer.ts
- src/tv2_afvd_showstyle/helpers/pieces/adlib.ts
- src/tv2_afvd_showstyle/parts/server.ts
- src/tv2_offtube_showstyle/__tests__/actions.spec.ts
- src/tv2_offtube_showstyle/cues/OfftubeAdlib.ts
- src/tv2_offtube_showstyle/parts/OfftubeServer.ts
Task description: When adlibbing server clips, cue ADLIBPIX=SERVER, studio mics should open or stay open.
Refactored to make distinction between VO-layers, which only VO parts and corresponding adlib actions have, and VO-levels which ADLIBPIX servers in offtube have too.
> feat: open mics on adlib servers (offtube)

- src/tv2-common/helpers/graphics/caspar/index.ts
- src/tv2-common/helpers/graphics/index.ts
- src/tv2_offtube_showstyle/cues/OfftubeGraphicDesign.ts
- src/tv2_offtube_showstyle/onTimelineGenerate.ts
Allow the TSR to merge/extend the objects, which makes controling one template from multiple mappings possible
Waiting for a TSR/Playout Gateway release
> fix: send html template data as objects

- src/tv2-common/updatePolicies/partProperties.ts
Some properties were not syncing on `syncIngestUpdateToPartInstance` when from defined they become undefined.
The new part comes from cache/db and loses all properties that were explicitly set to undefined or are no longer defined. 
We need to set them to undefined if we want them unset by `updatePartInstance`.
Complicated types should help spotting issues if `IBlueprintMutatablePart` changes in the future
> fix: undefined properties not synced

- src/tv2-common/helpers/postProcessDefinitions.ts
The externalId of the part is tied to the videoId field from iNews. This means that if the videoId changes, a new externalId is created and Sofie creates a new part, leaving an orphaned part instance if the part is set as next.
This PR removes the videoId from the externalId, relying on using the `padId` function applied to all parts to pad the externalId according to the elements position, which was already being done on top of the videoId.
This should be safe, as we only expect one Server per story.
> [SOF-541] fix: Don't create a new part when the server video Id is changed

- src/inews-mixins/__tests__/rundownDuration.spec.ts
- src/inews-mixins/playlist.ts
- src/inews-mixins/rundownDuration.ts
- src/tv2-common/getSegment.ts
- src/tv2-common/inewsConversion/converters/ParseBody.ts
- src/tv2-common/inewsConversion/converters/ParseCue.ts
- src/tv2-common/inewsConversion/converters/__tests__/body-parser.spec.ts
- src/tv2-common/migrations/shortcuts.ts
- src/tv2-common/types/index.ts
- src/tv2-common/types/inews.ts
- src/tv2_afvd_showstyle/migrations/index.ts
- src/tv2_offtube_showstyle/migrations/index.ts
The total duration of a rundown will now be calculated as the sum of the total time of all segments up to ~~and including~~ the first continuity story. Floated segments will not be included in the total rundown duration.
> fix: Ignore floated segments, count time only until first continuity story

- src/tv2-common/parts/server.ts
When importing a video clip from iNews it will now use the type (server, vo, vov) as title instead of the videoId.
Have also tried rewriting the function to make it more readable
> feat: show type instead of videoId when queing a clip

- src/tv2-common/cues/ekstern.ts
- src/tv2-common/inewsConversion/converters/ParseBody.ts
- src/tv2-common/inewsConversion/converters/ParseCue.ts
- src/tv2_afvd_showstyle/parts/live.ts
Use the title coming from the primary cue's source for Ekstern parts. It will say ‘LIVE 1’, ‘FEED 1’, ‘SKYPE 1’ etc.
> fix: Use cue source for ekstern part name

- src/tv2-common/cues/ekstern.ts
- src/tv2-common/cues/index.ts
- src/tv2-common/cues/mixMinus.ts
- src/tv2-common/evaluateCues.ts
- src/tv2-common/inewsConversion/converters/ParseCue.ts
- src/tv2-common/inewsConversion/converters/__tests__/cue-parser.spec.ts
- src/tv2-constants/enums.ts
- src/tv2_afvd_showstyle/helpers/pieces/evaluateCues.ts
- src/tv2_afvd_showstyle/migrations/sourcelayer-defaults.ts
- src/tv2_afvd_studio/layers.ts
- src/tv2_offtube_showstyle/migrations/sourcelayer-defaults.ts
- src/tv2_offtube_studio/layers.ts
- src/tv2_offtube_studio/migrations/mappings-defaults.ts
Adds the `MINUSKAM` cue which can be used to set the mix minus source for live sources.
Currently this will only work for AFVD because the QBoxes do not have a mix minus controlled by Sofie. An abstract mapping has been created as a placeholder for future work when a mix minus is required.
> feat: MINUSKAM cue

- src/tv2-common/inewsConversion/converters/ParseCue.ts
Fixes a bug where timed graphics did not show in VO parts. The pieces were created, but parent class used in the timelineObjects was not generated in VO parts, so `enable` on the graphic pieces had this condition `while: ".undefined & !.adlib_deparent & !.full"`.
> fix: create parent class for VOs

- src/inews-mixins/playlist.ts
- src/inews-mixins/rundownDuration.ts
- src/tv2-common/getSegment.ts
- src/tv2-common/inewsConversion/index.ts
- src/tv2-common/inewsConversion/time.ts
- src/tv2-common/time/partTime.ts
- src/tv2-common/types/inews.ts
- src/tv2_afvd_showstyle/__tests__/blueprint.spec.ts
- src/tv2_afvd_showstyle/helpers/time.ts
- src/tv2_afvd_showstyle/parts/kam.ts
- src/tv2_offtube_showstyle/getRundown.ts
This fixes the bug we saw in AFVD where the segment timeline container crashed on the on-air queue. This was caused by the `budgetDuration` of a part being `NaN`. I have copied the typings from Jesper's work in the iNews gateway last week and written a new helper function to convert times from iNews to numbers, falling back to `0` which I think works for all of the cases I've found in blueprints?
> fix: Fields from iNews may be undefined causing NaN to appear in UI

- src/tv2-common/actions/executeAction.ts
- src/tv2-common/evaluateCues.ts
- src/tv2-common/helpers/graphics/caspar/index.ts
- src/tv2-common/helpers/graphics/internal/index.ts
- src/tv2-common/helpers/graphics/pilot/index.ts
- src/tv2-common/helpers/graphics/timing.ts
- src/tv2-common/helpers/graphics/viz/index.ts
- src/tv2-common/parts/effekt.ts
- src/tv2_afvd_showstyle/actions.ts
- src/tv2_afvd_showstyle/helpers/pieces/__tests__/grafikViz.spec.ts
- src/tv2_afvd_showstyle/helpers/pieces/__tests__/telefon.spec.ts
- src/tv2_afvd_showstyle/helpers/pieces/graphic.ts
- src/tv2_afvd_showstyle/helpers/pieces/graphicPilot.ts
- src/tv2_afvd_showstyle/helpers/pieces/telefon.ts
- src/tv2_afvd_showstyle/parts/cueonly.ts
- src/tv2_afvd_showstyle/parts/grafik.ts
- src/tv2_afvd_showstyle/parts/intro.ts
- src/tv2_afvd_showstyle/parts/unknown.ts
- src/tv2_afvd_studio/__tests__/graphics.spec.ts
- src/tv2_offtube_showstyle/actions.ts
- src/tv2_offtube_showstyle/cues/OfftubeGraphics.ts
- src/tv2_offtube_showstyle/parts/OfftubeDVE.ts
- src/tv2_offtube_showstyle/parts/OfftubeGrafik.ts
- src/tv2_offtube_showstyle/parts/OfftubeUnknown.ts
When taking a server part, the cut to the server input is delayed by `CasparPrerollDuration` ms.  The server part also has that value applied as `prerollDuration`, to keep previous timeline objects alive during that period. Unfortunately when the server part features an `SS=SC-LOOP` cue, and we're cutting from a part that had pilot graphics on the WALL, the WALL cuts immediately, not waiting the preroll duration.
~~This PR solves the issue by setting a higher priority on Pilot graphics targeting WALL, so that the timeline object is still alive and on top during `prerollDuration`.~~
This PR solves the issue by setting a `start` equal to `prerollDuration` or `transitionPrerollDuration` in the WALL's timelineObject. It also updates this value when executing the take-with-transition adlib …
> fix: delay WALL graphics when part has preroll

- config/webpack.config.js
bump hardcoded version to avoid error messages on blueprints when deploying release 37
> fix: bum version to avoid version mismatch error message in core

- src/tv2-common/migrations/index.ts
This runs for multiple tables, so we need to make the ids different, otherwise Core complains.
> fix: duplicate migration step id

- src/tv2-common/__tests__/util.spec.ts
- src/tv2-common/util.ts
prevent from removing double backslash at the beginning
> fix: win shares joining

- src/tv2-common/parts/invalid.ts
Invlaid parts will no longer mark themselves as autoNext, as core will prevent them from being taken in the first place.
> fix: Remove autoNext from invalid parts

- src/tv2-common/migrations/forceSourceLayerToDefaultsBase.ts
- src/tv2_afvd_showstyle/migrations/index.ts
- src/tv2_afvd_showstyle/migrations/sourcelayer-defaults.ts
- src/tv2_afvd_showstyle/migrations/util.ts
- src/tv2_offtube_showstyle/migrations/index.ts
- src/tv2_offtube_showstyle/migrations/sourcelayer-defaults.ts
- src/tv2_offtube_showstyle/migrations/util.ts
This change allows transition pieces (e.g. Intro / KAM CS 3) to be found by the presenter screen and used as the primary piece. This will make the presenter clock show the correct colour for these kinds of pieces.
This PR requires this work in core: https://github.com/tv2/tv-automation-server-core/pull/97
> fix: Add Jingle layers to presenter screen

- src/inews-mixins/__tests__/playlist.spec.ts
- src/inews-mixins/__tests__/rundownDuration.spec.ts
- src/inews-mixins/playlist.ts
Makes it work as specified in SOF-549: the rundown is back-timed only if the first Continuity has back-time.
Note: unit testing `getRundownWithBackTime` is not perfect and we already have tests for `getRundownDuration`, but I think it might be better to revisit this when enabling breaks because I expect more changes.
> fix: back-time valid only when on first continuity

- src/tv2-common/migrations/shortcuts.ts
- src/tv2_afvd_showstyle/migrations/index.ts
- src/tv2_offtube_showstyle/migrations/index.ts
- src/tv2_system/migrations/hotkeys.ts
Disable default system-wide triggers instead of removing them, so that the core and system migrations don't fight with each other.
Remove stale migrations that could cause errors because of referencing non-existent properties and layers.
> Fix(SOF-762): migrations failing

- src/tv2-common/hotkeys/helpers/cutToBox.ts
- src/tv2-common/hotkeys/helpers/queue.ts
- src/tv2-common/hotkeys/helpers/studioSource.ts
- src/tv2-common/hotkeys/local.ts
- src/tv2-common/hotkeys/server.ts
- src/tv2_afvd_showstyle/getRundown.ts
live and server was also filtered by either full_audio_level or vo_audio_level, without having the tags.
> fix: Use full or VO tags only for EVS.

- src/tv2-common/content/dve.ts
- src/tv2-common/sources.ts
Since the custom hotkey labels were removed from EVS shortcuts, `100%` was removed from labels for keyboard preview.
To re-enable `100%` was added via `localSourceName`.
The logic for converting this into a source id, was not flexible enough to allow for the `100%` so for `EVS 1 100%`, it looked for the source `1100` instead of `1`.
> Sof 823/evs 100 percent not working

- shelf-layouts/AFVD_Default_showstyle_hotkeys.json
The generated AutoHotKey script broke F5 cut to cam 5 functionality, since it mapped to an unused key combo.
> fix: Removed F5 from custom hotkey labels.

- package.json
- yarn.lock
Node-license-validator was dependent on a library that was dependent on library that had bug when we remove dependencies from package.json.
The second library hasn't been updated for years, so waiting around for a fix isn't really feasable.
Instead we now use license-checker to check the licenses of our dependencies.
> Use license-checker instead of node-license-validator

- src/tv2-common/content/server.ts
- src/tv2-common/parts/server.ts
- src/tv2_afvd_showstyle/helpers/pieces/adlib.ts
Same as https://github.com/tv2/sofie-blueprints-inews/pull/103 but targeting develop where audio persistence was rewritten.
> SOF-932: Server adlibs and VO parts should have VO-level audio (develop)

- src/tv2-common/inewsConversion/converters/ParseBody.ts
- src/tv2-common/inewsConversion/converters/ParseCue.ts
- src/tv2-common/inewsConversion/converters/__tests__/body-parser.spec.ts
Blueprints now strips GraphicDesign and BackgroundLoop cues that is not from the iNews layout, if there is an iNews layout cue that also has a configuration in blueprints
> SOF-930 Fallback on regular cues when no config for layout cues

- src/tv2-common/actions/executeAction.ts
Seems like there was a small change in core, `stoppedPlayback` for currently playing pieceInstances used to be undefined, but now is 0 instead
> fix: SOF-943 failing to set source to box

- src/tv2-common/cues/lyd.ts
- src/tv2_afvd_showstyle/helpers/pieces/__tests__/lyd.spec.ts
Add the Flow Producer tag because we're filtering by it in the "_overlay, graphic, soundbed_" dashboard panel.
> fix: SOF-934 show LYD adlibs in the shelf

- src/tv2-common/inewsConversion/converters/ParseBody.ts
- src/tv2-common/inewsConversion/converters/__tests__/body-parser.spec.ts
Now `EVSXVO`, `EVS XVO`, `EVSX VO`, `EVS X VO` are all parsed as the same thing.
> fix: SOF-833 allow extra space in EVS X VO

- src/tv2-common/cues/lyd.ts
- src/tv2_afvd_showstyle/helpers/pieces/__tests__/lyd.spec.ts
Now blueprints generate LYD fade with the fadetime send to the SisyfosAudioBedLayer.
If there is a fadetime we tell Sisyfos to turn off the channel immediately because Sisyfos won't start fading untill it has been told to turn of the channel.
So if there is a fadetime of 2000ms we tell Sisyfos that isPgm should be 0 and Sisyfos will then start a fade that takes 2000 ms
> Sof 937/fade audio bed

- package.json
- src/tv2-common/content/jingle.ts
- src/tv2_offtube_showstyle/cues/OfftubeJingle.ts
- src/tv2_offtube_studio/layers.ts
- src/tv2_offtube_studio/migrations/index.ts
- src/tv2_offtube_studio/migrations/mappings-defaults.ts
Fixes the issue causing the first frame of all offtube jingles to be preloaded and shown on PGM regardless of the LoadFirstFrame setting.
Refactors some layer names to be less confusing.
> fix: SOF-975 make offtube jingles respect LoadFirstFrame setting

- shelf-layouts/Q_Flow_Rundown_View_Layout.json
The `exposeAsSelectableLayout` is only available to Rundown View Layouts, so we need a new Rundown View Layout layout that uses the Q flow Shelf Layout
> chore: SOF-1006 add Q Flow rundown view layout

- src/tv2-common/content/server.ts
- src/tv2-common/getSegment.ts
- src/tv2-common/parts/server.ts
- src/tv2-common/pieces/adlibServer.ts
- src/tv2_afvd_showstyle/helpers/pieces/adlib.ts
- src/tv2_afvd_showstyle/parts/server.ts
- src/tv2_offtube_showstyle/cues/OfftubeAdlib.ts
- src/tv2_offtube_showstyle/parts/OfftubeServer.ts
Makes seeking work for resumed clips. (in TSR `seek` requires `length` to be provided)
Also refactors some functions by grouping params.
> fix: SOF-767 set `length` for clips with `seek`

- src/tv2-common/__tests__/jinglePartProperties.spec.ts
- src/tv2-common/jinglePartProperties.ts
Fixes jingles ending too early.
(After release41 changes in core, `expectedDuration` has to include the `autoNextOverlap` time)
> fix: SOF-942 jingles expected durations

- config/tsconfig.strict.json
- src/__mocks__/context.ts
- src/tv2-common/actions/context.ts
- src/tv2-common/helpers/graphics/pilot/index.ts
- src/tv2-common/migrations/__tests__/migrationContext.mock.ts
Fixes missing missing `externalId` on pieces that led to failing to ingest the rundown/segment.
Enables `strictPropertyInitialization` compiler option to avoid such bugs in the future
> fix: SOF-1022 missing externalId on pieces

- src/tv2_afvd_showstyle/getRundown.ts
Reintroducing the call that makes the 'EVS X 100' cut-to-dve-box adlib.
It looks like it was lost in a merge.
> fix: SOF-1057 Creates cut-to-dve-box addlibs for EVS X 100 again

- src/tv2-common/content/jingle.ts
The end-alpha still needs to be subtracted from the `sourceDuration` so that the `PieceCountdownPanel` counts down to the start of the transition. The freeze indicator, on the other hand, takes `sourceDuration + postrollDuration` into consideration so we can put the end-alpha there.
> fix: SOF-1079 set postrollDuration on jingles to offset the freeze indicator

- shelf-layouts/Rundown_Header_Layout.json
Fixed position of part countdown label and height of black box in header of rundown view.
> fix: Updated black box in header to correct position and size.

- src/tv2-common/content/server.ts
We don't need it when `seek` is not set. (Caspar needs it just for the purpose of `seek` working, but the values are incompatible with version 2.3 - it would need more work to get Server Resume compatible with that version)
> fix: SOF-767 set `length` only when `seek` is truthy

- src/tv2-common/actions/executeAction.ts
- src/tv2-common/content/server.ts
- src/tv2-common/pieces/adlibServer.ts
Re-enables Server Resume and adds some parameters to the timeline object, to make looping work correctly with CasparCG 2.1
> fix: SOF-767 re-enable server resume

- src/tv2-common/actions/actionTypes.ts
- src/tv2-common/actions/executeAction.ts
- src/tv2-common/evaluateCues.ts
- src/tv2_afvd_showstyle/helpers/pieces/adlib.ts
- src/tv2_afvd_showstyle/helpers/pieces/dve.ts
- src/tv2_offtube_showstyle/__tests__/actions.spec.ts
- src/tv2_offtube_showstyle/cues/OfftubeAdlib.ts
- src/tv2_offtube_showstyle/cues/OfftubeDVE.ts
Fixed by replacing DVE AdLib Pieces with AdLib Actions. The former seem to be affected by some `prerollDuration` bug in core, which probably does not make sense to look into before we reach NRKs release42 and can update superfly-timeline to a newer version.
> fix: SOF-1134 color source shown briefly before DVE

- shelf-layouts/Kommentator.json
- shelf-layouts/Q flow.json
Update layout values to fit with the new scaling of release 42.
Not sure if the sourceLayerIds of the qFlow layout is the exact correct ones. If you notice some missing or some that shouldn't be there, let me know.
> Update kommentator and qFlow layout

- package.json
- src/tv2-common/blueprintConfig.ts
- src/tv2-common/inewsConversion/converters/ParseCue.ts
- src/tv2-common/inewsConversion/converters/__tests__/cue-parser.spec.ts
- src/tv2-common/migrations/index.ts
- src/tv2_afvd_showstyle/__tests__/blueprint.spec.ts
- src/tv2_afvd_showstyle/__tests__/config-manifest.spec.ts
- src/tv2_afvd_showstyle/__tests__/configs.ts
- src/tv2_afvd_showstyle/config-manifests.ts
- src/tv2_afvd_showstyle/migrations/index.ts
- src/tv2_offtube_showstyle/__tests__/config-manifest.spec.ts
- src/tv2_offtube_showstyle/config-manifests.ts
This PR adds the GFX Design table, and migrates the entries from GFX templates into it. ParseCue has been altered to ensure that it fits the purpose, and unlike it was originally described, the Style will have priority over Name.
> Sof 1092/create gfx design template

- src/tv2-common/inewsConversion/converters/ParseBody.ts
- src/tv2-common/inewsConversion/converters/__tests__/body-parser.spec.ts
Now limit the duration of a transition to 250 frames if we receive a longer transition than the Atem allows
> SOF-1121 Set max duration on transition effects

- src/tv2_afvd_showstyle/parts/kam.ts
- src/tv2_offtube_showstyle/parts/OfftubeKam.ts
Only look for 'cs' when creating the cam cs 3 part. 
Galleries now uses sourceDefintion for determining to create a cam cs 3 part instead of rawType
> SOF-1171 Not creating 'cam cs 3' when there is whitespace

- src/tv2-common/blueprintConfig.ts
- src/tv2_afvd_showstyle/config-manifests.ts
- src/tv2_offtube_showstyle/config-manifests.ts
(Does not rename the underlying `VizTemplate` property to avoid messing things up at the last minute with migrations, but adds comments)
> fix: SOF-1192 readd the Template Name column and update descriptions

- config/webpack.config.js
- src/tv2-common/actions/executeAction.ts
- src/tv2-common/helpers/graphics/InternalGraphic.ts
- src/tv2-common/onTimelineGenerate.ts
- src/tv2_afvd_showstyle/helpers/pieces/__tests__/grafikViz.spec.ts
- src/tv2_afvd_showstyle/helpers/pieces/__tests__/telefon.spec.ts
When recalling last DVE, now also recall the Ident of said DVE.
Fixed a bug where Recall las Live would also recall a Ident if there had been any Live with an Ident on air even though that Ident did not belong to the recalled Live
> Sof 1141/last dve doesnt bring back ident

- src/tv2_afvd_showstyle/config-manifests.ts
- src/tv2_offtube_showstyle/config-manifests.ts
- src/tv2_offtube_showstyle/migrations/index.ts
The same migration that is used for AFVD was missing for the QBoxes, this has now been added. Furthermore, an issue was discovered with the way that default values are used to populate GFXTemplates, this has been altered so they are rightly divided as GFXTemplates and GfxDesignTemplates.
I, however, do not think this is an ideal way of populating the tables by default, but this should fix the issue for now.
> Sof 1202/Gfx Design template migration

- src/tv2-common/helpers/graphics/pilot/index.ts
Forgot the SOF tag in the commit.
> SOF-769 - fix: adds Kommentator tag to created Adlibs Pieces.

- src/tv2-common/actions/executeAction.ts
- src/tv2-common/blueprintConfig.ts
- src/tv2-common/evaluateCues.ts
- src/tv2-common/helpers/graphics/caspar/__tests__/htmlPilotGraphicGenerator.spec.ts
- src/tv2-common/helpers/graphics/caspar/index.ts
- src/tv2-common/helpers/graphics/design/index.ts
- src/tv2-common/helpers/graphics/viz/index.ts
- src/tv2-common/showstyle/config-manifests.ts
- src/tv2_afvd_showstyle/__tests__/configs.ts
- src/tv2_afvd_showstyle/config-manifests.ts
- src/tv2_afvd_showstyle/helpers/config.ts
- src/tv2_offtube_showstyle/helpers/config.ts
Now _HTML Package Folder_ is the common column between Graphics Setups in both Show Styles, used for the HTML template name (for locators in Gallery, and for all the graphics in Qboxes).
> fix: SOF-1201 use a different column for the HTML graphics template name

- src/tv2-common/actions/executeAction.ts
Wraps the Ident in a new object before inserting it into the part. This is how Recall last live does it.
> Sof 1141/recall last dve ident only appears in gui

- shelf-layouts/Kommentator.json
Include sourceLayer for pilot overlay graphics in KG elements in kommentator shelf
> fix: SOF-769 Add missing sourceLayer in kommentator shelf

- src/tv2_afvd_studio/getBaseline.ts
We are going to purge the MSE shows on activation, so there is no longer a need for a timelineObject in the baseline telling TSR to purge the MSE
> SOF-1081 No longer clear MSE shows in baseline

- package.json
- src/tv2-common/actions/executeAction.ts
- src/tv2-common/evaluateCues.ts
- src/tv2-common/helpers/graphics/design/index.ts
- src/tv2-common/helpers/graphics/viz/index.ts
- src/tv2_afvd_showstyle/getRundown.ts
- src/tv2_afvd_showstyle/helpers/pieces/__tests__/grafikViz.spec.ts
- src/tv2_afvd_showstyle/helpers/pieces/__tests__/telefon.spec.ts
- src/tv2_afvd_showstyle/helpers/pieces/clearGrafiks.ts
- src/tv2_afvd_showstyle/helpers/pieces/graphicBackgroundLoop.ts
- src/tv2_afvd_showstyle/helpers/pieces/showLifecycle.ts
- yarn.lock
Note: Not a draft, but the tests won't pass on this branch until updating the TSR types, which I'll do after merging https://github.com/tv2/tv-automation-state-timeline-resolver/pull/41
Uses new TSR types where the `showId`/`showIds` is replaced by the human-readable `showName`/`showNames`, and resolved in the TSR using the MSE's directory. 
No migrations because the property names were already changed, but manual config change is needed in the Graphics Setups table after deployment.
> feat: SOF-1065 use showName(s) instead of showId(s)

- src/tv2-common/actions/executeAction.ts
- src/tv2_afvd_showstyle/actions.ts
- src/tv2_offtube_showstyle/actions.ts
Make `RESET` the default trigger mode for the Server Select action in the Qbox (Offtube) Show Style to prevent servers from stopping in the middle.
> fix: SOF-1290 disable Server Resume in Qboxes

- src/tv2-common/parts/effekt.ts
adds the preroll to the piece duration in order to prevent cutting off frames at the end
> fix: SOF-1260 fix duration of effects

- src/tv2-common/actions/executeAction.ts
- src/tv2-common/content/dve.ts
- src/tv2-common/videoSwitchers/TriCaster.ts
- src/tv2-common/videoSwitchers/__tests__/TriCaster.spec.ts
- src/tv2-common/videoSwitchers/types.ts
Instead of modifying layout of a planned DVE, makes the DVE adlib action queue a new part.
When modifying a dynamically inserted DVE, modifies the piece name, and fills in sources that may have not been defined in the previous layout.
Fixes a minor TriCaster-related bug where `input0` (non-existent in TriCaster) was selected instead of `black`
> fix: SOF-1403 adlibing DVEs before planned ones

- src/tv2-common/actions/actionTypes.ts
- src/tv2-common/actions/executeAction.ts
- src/tv2_afvd_showstyle/GlobalAdlibActionsGenerator.ts
- src/tv2_afvd_showstyle/__tests__/actions.spec.ts
- src/tv2_offtube_showstyle/__tests__/actions.spec.ts
- src/tv2_offtube_showstyle/getRundown.ts
Able to create ActionTriggers for Live that cuts directly to program.
This is basically extracting the code from `executeActionCutToCamera` that determines when and how to cut directly and make `executeActionCutToRemote` use the extracted code.
Naming suggestions for `executePiece` is much appreciated. If you want me to refactor `executePiece` further, let me know (currently just extracted it and changed some variable names)
> SOF-1374 Live cuts directly

- src/tv2-common/blueprintConfig.ts
- src/tv2-common/helpers/config.ts
- src/tv2-common/showstyle/config-manifests.ts
- src/tv2_afvd_showstyle/__tests__/config-manifest.spec.ts
- src/tv2_afvd_showstyle/__tests__/configs.ts
- src/tv2_afvd_showstyle/helpers/config.ts
- src/tv2_offtube_showstyle/helpers/config.ts
Now uses DefaultSetupName in TableConfigItemGfxDefaults instead of GfxSetup since these were two different names for the same field.
Changed the type to match actually stored in the database.
> SOF-964 Able to find SelectedGfxSetup using GfxDefaults

- src/tv2-common/actions/CoreActionExecutionContext.ts
- src/tv2-common/actions/executeAction.ts
- yarn.lock
Cutting directly now creates a new Part instead of just switching the piece in the current part.
Directly cut parts are not able to be recalled as last live.
> SOF-1374 Don't recall LIVEs that has been cut directly.

- src/tv2-common/__tests__/calculate-time.spec.ts
- src/tv2-common/blueprintConfig.ts
- src/tv2-common/cueTiming.ts
- src/tv2-common/evaluateCues.ts
- src/tv2-common/inewsConversion/converters/ParseBody.ts
- src/tv2-common/inewsConversion/converters/ParseCue.ts
- src/tv2-common/inewsConversion/converters/__tests__/body-parser.spec.ts
- src/tv2-common/types/inews.ts
- src/tv2-constants/enums.ts
- src/tv2_afvd_showstyle/__tests__/configs.ts
- src/tv2_afvd_showstyle/helpers/pieces/evaluate-cue-graphic-schema.ts
- src/tv2_afvd_showstyle/helpers/pieces/evaluateCues.ts
- src/tv2_afvd_showstyle/layers.ts
- src/tv2_afvd_showstyle/migrations/sourcelayer-defaults.ts
- src/tv2_afvd_studio/layers.ts
- src/tv2_afvd_studio/migrations/mappings-defaults.ts
It is now possible to parse Schema cues from iNews and send them to Viz.
The Schema and Design cues are now parsed from the iNews.fields instead of finding the fields cues in the iNews body.
Old code for parsing Design fields cue from the body has been deleted.
> Sof 1422/send schema to mse

- src/tv2-common/content/server.ts
`noStarttime` prevents seeking to an undesired timecode when a transition or next part's preroll begins
> fix: SOF-1127 server audio jump on DVE end

- src/tv2-common/content/server.ts
- src/tv2-common/parts/server.ts
- src/tv2_offtube_showstyle/__tests__/actions.spec.ts
In order to fit the new way of building the Timeline it has been necessary to change the TimelineEnable of Servers.
Instead of using a "while some class" they now just start at 0. 
Also removed a TimelineObject which was supposed to ensure the Servers wasn't playing when it isn't on Air. Removing it seems to have had zero effect, so hence it is gone.
Funnily enough, this change still works with old Core.
> SOF-1539 No longer uses 'while x' for server Parts and Pieces. 

- src/tv2-common/content/dve.ts
- src/tv2_afvd_showstyle/helpers/content/dve.ts
- src/tv2_afvd_showstyle/helpers/pieces/dve.ts
In order for the new Actions to insert a Source on a planned DVE, we need some metadata on the planned DVE Piece.
This PR puts that metadata on said Piece.
> SOF-1694 Dve Piece now includes metadata needed for inserting Sources to inputs by Actions

- src/tv2-common/content/dve.ts
- src/tv2_afvd_showstyle/helpers/content/dve.ts
- src/tv2_afvd_showstyle/helpers/pieces/dve.ts
Renamed DVE content related to the new Sofie server to split screen.
> refactor: Sofie server related DVE content is renamed to SplitScreen.

- src/tv2-common/onTimelineGenerate.ts
- src/tv2-common/parts/server.ts
- src/tv2-constants/tv2-audio.mode.ts
- src/tv2_afvd_showstyle/parts/evs.ts
This PR introduces metadata for video clips and replays that can be used to reflect whether they have voice over. This is under a pieces metadata as `audioMode`.
> feat/ Add VO Metadata on Video Clips and Replays

- src/tv2-common/helpers/graphics/design/index.ts
- src/tv2-common/helpers/graphics/pilot/PilotGraphicGenerator.ts
- src/tv2-common/onTimelineGenerate.ts
- src/tv2-common/parts/server.ts
- src/tv2_afvd_showstyle/helpers/pieces/graphicBackgroundLoop.ts
- src/tv2_afvd_showstyle/helpers/pieces/jingle.ts
- src/tv2_offtube_showstyle/cues/OfftubeJingle.ts
This PR adds a `mediaId` property to the metadata of a piece, it's intended for use in the frontend to help decide the piece availability.
> SOF-1651 Metadata now contains a related mediaId property

- src/tv2_afvd_showstyle/__tests__/configs.ts
- src/tv2_afvd_studio/config-manifests.ts
- src/tv2_afvd_studio/layers.ts
- src/tv2_afvd_studio/migrations/index.ts
- src/tv2_afvd_studio/migrations/mappings-defaults.ts
- src/tv2_afvd_studio/migrations/util.ts
- src/tv2_afvd_studio/sisyfosChannels.ts
This PR contains:
- New Sisyfos EVS layer for track 3/4
- Rename old Sisyfos EVS layer track to include track 1/2
- Slight refactor in the horrible global test setup to make the test for EVS still parse since the Sisyfos layer no longer matched one to one with the EVS name...
> SOF-1781 Add Sisyfos EVS track 3/4

- src/tv2_afvd_studio/migrations/mappings-defaults.ts
- src/tv2_offtube_studio/migrations/mappings-defaults.ts
The default values for the layer mapping `casparcg_player_clip_pending` was pointing at values that would "deactivate" the lookahead functionality by saying the max search distance should be -1. 
This means that everytime we would run migrations, the layer mapping would change to an unusable value.
This PR changes the default values to be the values we actually want for lookahead, so a future migration won't ruin it.
> SOF-1823 Set proper default values for Server lookahead

- src/tv2-common/helpers/graphics/internal/InternalGraphic.ts
- src/tv2-common/onTimelineGenerate.ts
- src/tv2_afvd_showstyle/helpers/pieces/__tests__/grafikViz.spec.ts
- src/tv2_afvd_showstyle/helpers/pieces/__tests__/telefon.spec.ts
This PR adds the graphic template we receive from iNews into the piece metadata rather than us having to introduce the `content` property in our frontend. This is also to avoid using the confusing behaviour of the `content` properties having multiple purposes such as `fileName` being either a file name for a source or a type of graphic template such as "bundt".
> SOF-1636 - Adds content data for graphic template into metadata

- src/tv2-common/inewsConversion/converters/ParseBody.ts
- src/tv2-common/inewsConversion/converters/__tests__/body-parser.spec.ts
- src/tv2_afvd_showstyle/__tests__/configs.ts
After the changes to have an "audio track" on the EVS in https://github.com/tv2/sofie-blueprints-inews/pull/231, the ingested EVS from iNews could no longer find the correct sourceLayer.
This is solved by adding `1/2` to the EVS id.
> SOF-1824 Add 1/2 audio track to ingested EVS

- src/tv2-common/parts/server.ts
This is to fix the bug of multiple pieces being shown for video clips and voice overs. This is because we have a Selected Server for each Server piece. The selected server is not something we use in the GUI and i have therefore changed the metadata to not render it.
> SOF-1830 Set Selected Servers to Unknown and Remove Output Layer

- src/tv2-common/inewsConversion/converters/ParseBody.ts
- src/tv2-common/inewsConversion/converters/__tests__/body-parser.spec.ts
- src/tv2-common/inewsConversion/converters/__tests__/cue-parser.spec.ts
- src/tv2_afvd_showstyle/__tests__/blueprint.spec.ts
- src/tv2_afvd_showstyle/__tests__/configs.ts
- src/tv2_afvd_studio/__tests__/graphics.spec.ts
- src/tv2_offtube_showstyle/__tests__/actions.spec.ts
When parsing Remotes we now use both the 'LIVE' and 'number' part of the cue
Note: This change requires that the `Live mapping` studio blueprint configuration table has the name of the entries to be `LIVE X` instead of just `X`. For Live 1 it would look lik `LIVE 1`.
> SOF-1889 Use full name for Lives

- src/tv2-common/getSegment.ts
Add 'invalidity' field to Segment. Set the field if the Segment has both a MiniShelf and Parts.
> SOF-1979 Add 'invalidity' field to Segment

- src/tv2-common/helpers/graphics/pilot/PilotGraphicGenerator.ts
- src/tv2_afvd_studio/__tests__/graphics.spec.ts
Pilot Overlay graphics was getting a Preroll duration assigned them which allegedly doesn't seem needed. However, this preroll duration does delay the switching of the source in the videomixer which is not good, so the delay have been removed.
> SOF-2010 OVL pilot graphics no longer gets a prerollduration

- src/tv2-common/videoSwitchers/Atem.ts
- src/tv2-common/videoSwitchers/VideoSwitcher.ts
- src/tv2-common/videoSwitchers/__tests__/Atem.spec.ts
- src/tv2_afvd_showstyle/__tests__/transitions.spec.ts
- src/tv2_offtube_showstyle/__tests__/actions.spec.ts
When creating TimelineObjects for the VideoMixer, if there is a transition, create an extra Timelineobject for when the transition is over to update the value in the Preview in the VideoMixer.
Due to how VideoMixers works, we can't update the Preview while we are doing a transition. If we did, the transition would continue but it would use the updated value. We don't want that, so we have to wait untill the transition is over before updating the Preview. This is what the new TimelineObject does. It starts when the transition is over (plus a slight delay to avoid a race condition) and then updates the Preview.
Note: When we simply receive a CUT transition, we don't create a TimelineObject with transition properties. If we did, then the library `sofie-atem-state` would not update the …
> SOF-2119 Able to set Preview in VideoMixer

- src/tv2-common/actions/executeAction.ts
- src/tv2-common/evaluateCues.ts
- src/tv2-common/getSegment.ts
- src/tv2_afvd_showstyle/helpers/pieces/evaluateCues.ts
- src/tv2_afvd_showstyle/parts/evs.ts
- src/tv2_afvd_showstyle/parts/grafik.ts
- src/tv2_afvd_showstyle/parts/intro.ts
- src/tv2_afvd_showstyle/parts/kam.ts
- src/tv2_afvd_showstyle/parts/live.ts
- src/tv2_afvd_showstyle/parts/server.ts
- src/tv2_afvd_showstyle/parts/teknik.ts
- src/tv2_afvd_showstyle/parts/unknown.ts
- src/tv2_afvd_studio/__tests__/graphics.spec.ts
- src/tv2_offtube_showstyle/helpers/EvaluateCues.ts
- src/tv2_offtube_showstyle/parts/OfftubeDVE.ts
- src/tv2_offtube_showstyle/parts/OfftubeGrafik.ts
- src/tv2_offtube_showstyle/parts/OfftubeKam.ts
- src/tv2_offtube_showstyle/parts/OfftubeServer.ts
- src/tv2_offtube_showstyle/parts/OfftubeUnknown.ts
Previously, action ranks were calculated by segment rank and cue index in part. This caused actions generated from segments, with multiple parts to not have the right order and get mixed if more than one action is generated per part.
> SOF-2203: Uses part index in segment to assign action rank.

- src/tv2-common/helpers/graphics/caspar/__tests__/htmlPilotGraphicGenerator.spec.ts
- src/tv2-common/helpers/graphics/caspar/htmlPilotGraphicGenerator.ts
- src/tv2-common/helpers/graphics/caspar/util.ts
The opacity value which used to be `100` was passed all the way through to the CasparCG. The theory is that this used to be handled elsewhere before the TSR was updated. Changing it to `1` which is the correct CasparCG value (interval between 0 and 1) fixed the issue we experienced.
> SOF-2206/DVE Locators Look Weird Due to Wrong Opacity Value

- src/tv2-common/cues/lyd.ts
If we had a AudioBed Piece and a stop AudioBed Piece on the same Part from iNews, the AudioBed would continue to play after the stop Piece.
This was because the AudioBed TimelineObject had no `end` and would therefore continue playing after the stop TimelineObject was no longer on the Timeline.
Add a "stop" class to the stop TimelineObject, that the AudioBed listens for and stops when it finds.
> SOF-2289 Add STOP_ADUIO_BED class

- src/tv2-common/videoSwitchers/TriCaster.ts
In Alba we have introduced `TriCasterMixEffectContentType` on the ME content of TriCaster TimelineObject.
This is not something that Blueprints have supported and hence TimelineObjects generated from Bluerprints don't have this value.
So when Alba makes a check for it, like on line 308 in the snippet below, it will always return undefined.
So any flows in Alba that needs these values won't work.
This PR introduce these values in Blueprints for TriCaster ME TimelineObjects.
Note that to add this attribute the `&` syntax has been used. This is because Blueprints fetches the types from BlueprintIntegration and we would have to publish a new version of BlueprintIntegration if we wanted to include them there. Since this is Alba only, and we want to get rid of Blueprints, we are simply using …
> SOF-2454 Assign ME types to TriCaster ME content

- src/tv2-common/videoSwitchers/TriCaster.ts
- src/tv2-common/videoSwitchers/__tests__/TriCaster.spec.ts
For some reason, the TriCaster implementation has combined the TimelineObject for SplitScreen Boxes and SplitScreen DSK into the same TimelineObject. The way Atem does this is to have a separate TimelineObject for each of these.
Alba-server is implemented where SplitScreen Boxes and SplitScreen DSK are two separated TimelineObjects. So when Alba would insert an input into a SplitScreen, the DSK information would disappear, because Alba thought it was in a different TimelineObject. 
This PR moves the SplitScreen DSK information into a separate TimelineObject so the TimelineObject structure matches the same Atem and Alba-server is using.
> SOF-2499 TriCaster now creates a separate TimelineObject for SplitScreen DSK

- src/tv2-common/inewsConversion/converters/ParseBody.ts
- src/tv2-common/inewsConversion/converters/ParseCue.ts
- src/tv2-common/sources.ts
We now allow the cues for LIVEs and FEEDs to be whatever the SuperUsers may like. Only criteria is, that the cue in iNews must match the configured name of the Live or Feed. (We strip whitespaces and ignore casing so those are the exceptions.)
Note: This makes a slight change to how we match a "RemoteCue" to a "RemoteSource". Previously we would only look in either the Feeds table or the Lives table. Since we no longer required that the Cue contains "LIVE" or "FEED", we no longer know which table to look at. So now we just always look at both tables for both Lives and Feeds. (Removing the one of the last things that made Lives and Feeds different).
In order to reduce to risk of breaking something else I haven't deleted the "REMOTE" section of `getSourceDefinition` due to the spaghetti …
> SOF-2527 Allow freetext in FEEDS and LIVES cues

- src/tv2_afvd_showstyle/parts/voss.ts
This ensures that the active timeline object is protected from lookahead timeline objects.
> fix: Sets VOSS auxiliary timeline object priority to 1.

- src/tv2-common/getSegment.ts
The reason Sisyfos didnt open the fader on VO is because we didn't set the VO-properties when creating the part. We now do it the exact same way we would a regular VO.
> AG-559 - Set VO levels for VOSS upon part creation
